server.port=9180
spring.application.name=PAYMENT-SERVICE

spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultzone = http://localhost:8761/eureka/
eureka.instance.hostname=localhost 

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.file.name=/Users/dhunc2_mac/eclipse-workspaceNew/observability/log/payment-service.log

management.tracing.sampling.probability=1.0

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true

management.metrics.distribution.percentiles-histogram.greeting=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true


spring.devtools.restart.enabled=false

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.org.springframework.data.redis.cache: DEBUG
logging.level.org.springframework.cache.interceptor: TRACE

spring.mail.properties.mail.debug=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=c2kalita85@gmail.com
spring.mail.password=uoxv myif noyz sydz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
